### ISSUE TITLE
新闻中心访问有问题，加载找不到Widget.ArticleType.B

### ISSUE THREAD

**Issue by WeiweiCaiAcpt** [SeriaWei/ZKEACMS#392]
你好，根据你们Publish的步骤：
Use Publish.cmd or Publish.sh to publish the project. You can also use the command line below to publish:

$ dotnet tool install -g ZKEACMS.Publisher
$ ./src/ZKEACMS.WebHost/publish-zkeacms

我直接本地启动PublishOutput路径下的ZKEACMS.WebHost.exe， 然后用本地的Edge浏览器访问http://localhost:5000
其他功能一切正常，但是在访问新闻中心的菜单时，出现以下错误：
![image](https://user-images.githubusercontent.com/70355356/100562198-e1b45400-32f5-11eb-8703-fe8c75970d5e.png)

在命令行窗口中，出现的是以下错误信息：
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The partial view 'Widget.ArticleType.B' was not found. The following locations were searched:
/wwwroot/themes/Default/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/themes/Default/Views/Widget.ArticleType.B.cshtml
/wwwroot/themes/Default/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Article/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Article/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Article/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.FormGenerator/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.FormGenerator/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.FormGenerator/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.GlobalScripts/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.GlobalScripts/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.GlobalScripts/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Message/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Message/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Message/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Product/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Product/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Product/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Redirection/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Redirection/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Redirection/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SectionWidget/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SectionWidget/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SectionWidget/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Shop/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Shop/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Shop/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Sitemap/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Sitemap/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Sitemap/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SiteSearch/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SiteSearch/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.SiteSearch/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.StyleEditor/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.StyleEditor/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.StyleEditor/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.TemplateImporter/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.TemplateImporter/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.TemplateImporter/Views/Shared/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Updater/Views/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Updater/Views/Page/Widget.ArticleType.B.cshtml
/wwwroot/Plugins/ZKEACMS.Updater/Views/Shared/Widget.ArticleType.B.cshtml
/Views/Widget.ArticleType.B.cshtml
/Views/Page/Widget.ArticleType.B.cshtml
/Views/Shared/Widget.ArticleType.B.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at ZKEACMS.HtmlHelperExtend.DisplayWidgetPart(IHtmlHelper html, WidgetViewModelPart widget) in C:\.NETCoreUpgradeApps\AppSources\ZKEACMS\src\ZKEACMS\Extend\HtmlHelperExtend.cs:line 37
   at AspNetCore.Views_Shared_DisplayWidget.ExecuteAsync() in C:\.NETCoreUpgradeApps\AppSources\ZKEACMS\src\ZKEACMS.WebHost\Views\Shared\DisplayWidget.cshtml:line 18
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at ZKEACMS.HtmlHelperExtend.DisplayWidget(IHtmlHelper html, WidgetViewModelPart widget) in C:\.NETCoreUpgradeApps\AppSources\ZKEACMS\src\ZKEACMS\Extend\HtmlHelperExtend.cs:line 27
   at AspNetCore.Views_Page_PreView.ExecuteAsync() in C:\.NETCoreUpgradeApps\AppSources\ZKEACMS\src\ZKEACMS.WebHost\Views\Page\PreView.cshtml:line 26
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

请问，是都publish的时候，少了什么东西没有被publish到相应的文件夹下？

**Comment by SeriaWei** [comment]
社区版里面并不包含`Widget.ArticleType.B`这个模板

**Comment by WeiweiCaiAcpt** [comment]
好的，谢谢说明。
