### ISSUE TITLE
Debug开发环境运行项目网站无法访问

### ISSUE THREAD

**Issue by brack7n** [SeriaWei/ZKEACMS#415]
按文档步骤调试运行项目，无法访问服务，使用`Publsh.cmd`发布的版本用`dotnet`命令行可以正常运行并访问

参考：
[官方文档->ZKEACMS 开发入门与扩展](http://www.zkea.net/zkeacms/document/startdev)
[官方文档视频->开发环境运行纸壳CMS](http://www.zkea.net/zkeacms/videos/view/start-dev.html)

![QQ图片20210226175325](https://user-images.githubusercontent.com/28703863/109285158-ae815280-785b-11eb-8e0e-9e446806bb27.png)

在**DEBUG**解决方案输出文件夹下手动运行
```
PS G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost\bin\Debug\net5.0> dotnet ZKEACMS.WebHost.dll
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Easy.Mvc.Plugin.Loader.GetPlugins()+MoveNext() in G:\Source\Repos\ZKEACMS\src\EasyFrameWork\Mvc\Plugin\Loader.cs:line 68
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Easy.Mvc.Plugin.Loader.LoadEnablePlugins(IServiceCollection serviceCollection) in G:\Source\Repos\ZKEACMS\src\EasyFrameWork\Mvc\Plugin\Loader.cs:line 37
   at Easy.Builder.LoadAvailablePlugins(IServiceCollection services) in G:\Source\Repos\ZKEACMS\src\EasyFrameWork\Builder.cs:line 125
   at ZKEACMS.Builder.UseZKEACMS(IServiceCollection services, IConfiguration configuration) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Builder.cs:line 251
   at ZKEACMS.WebHost.Startup.ConfigureServices(IServiceCollection services) in G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost\Startup.cs:line 43
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ZKEACMS.WebHost.Program.Main(String[] args) in G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost\Program.cs:line 18
```

clone项目后生成解决方案，解决方案输出文件信息
```
    目录: G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost\bin\Debug\net5.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2021/2/26     17:50                cs
d-----         2021/2/26     17:50                de
d-----         2021/2/26     17:50                es
d-----         2021/2/26     17:50                fr
d-----         2021/2/26     17:50                it
d-----         2021/2/26     17:50                ja
d-----         2021/2/26     17:50                ko
d-----         2021/2/26     17:50                pl
d-----         2021/2/26     17:50                pt-BR
d-----         2021/2/26     17:50                ref
d-----         2021/2/26     17:50                refs
d-----         2021/2/26     17:50                ru
d-----         2021/2/26     14:56                runtimes
d-----         2021/2/26     17:50                tr
d-----         2021/2/26     17:50                zh-Hans
d-----         2021/2/26     17:50                zh-Hant
-a----         2021/2/26     15:28            618 appsettings.json
-a----         2021/2/26     14:53            796 bower.json
-a----         2021/2/26     14:53           5037 bundleconfig.json
-a----        2018/11/15     20:02         105984 CacheManager.Core.dll
-a----         2021/2/26     14:53            361 compilerconfig.json
-a----         2020/7/17     18:55        4905864 DocumentFormat.OpenXml.dll
-a----         2021/2/26     17:50         285184 EasyFrameWork.dll
-a----         2021/2/26     17:50         155424 EasyFrameWork.pdb
-a----          2020/7/6     14:01          14336 IdGen.dll
-a----         2020/12/1     23:22          38280 Microsoft.AspNetCore.Authentication.JwtBearer.dll
-a----         2020/12/1     23:19          54152 Microsoft.AspNetCore.JsonPatch.dll
-a----         2020/12/1     23:22          62856 Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll
-a----         2020/12/1     23:19          80256 Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
-a----         2020/12/1     23:22          62856 Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll
-a----         2020/12/1     23:18         949128 Microsoft.AspNetCore.Razor.Language.dll
-a----        2020/11/12      0:15        5545352 Microsoft.CodeAnalysis.CSharp.dll
-a----        2020/11/12      0:14        2447752 Microsoft.CodeAnalysis.dll
-a----         2020/12/1     23:19          84360 Microsoft.CodeAnalysis.Razor.dll
-a----         2020/8/25     23:24         351704 Microsoft.Data.SqlClient.dll
-a----        2020/11/26      5:31         151432 Microsoft.Data.Sqlite.dll
-a----         2020/6/17      4:37          23424 Microsoft.DotNet.PlatformAbstractions.dll
-a----        2020/11/26      5:31          28552 Microsoft.EntityFrameworkCore.Abstractions.dll
-a----        2020/11/26      5:31        1825160 Microsoft.EntityFrameworkCore.dll
-a----        2020/11/26      5:31        1254280 Microsoft.EntityFrameworkCore.Relational.dll
-a----        2020/11/26      5:31         183176 Microsoft.EntityFrameworkCore.Sqlite.dll
-a----        2020/11/26      5:31         350080 Microsoft.EntityFrameworkCore.SqlServer.dll
-a----        2020/11/26      1:59          74120 Microsoft.Extensions.DependencyInjection.dll
-a----        2020/10/19     18:49          69000 Microsoft.Extensions.DependencyModel.dll
-a----         2020/5/18     20:11        1280952 Microsoft.Identity.Client.dll
-a----         2020/6/30      1:04          61288 Microsoft.IdentityModel.JsonWebTokens.dll
-a----         2020/6/30      1:05          24952 Microsoft.IdentityModel.Logging.dll
-a----         2020/6/30      1:06          32616 Microsoft.IdentityModel.Protocols.dll
-a----         2020/6/30      1:13         108904 Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
-a----         2020/6/30      1:09         862568 Microsoft.IdentityModel.Tokens.dll
-a----        2020/11/10     17:40         558592 MySqlConnector.dll
-a----        2018/11/27     23:10          97720 Newtonsoft.Json.Bson.dll
-a----         2019/4/22      1:06         669608 Newtonsoft.Json.dll
-a----        2020/11/12      4:16         323584 Pomelo.EntityFrameworkCore.MySql.dll
-a----          2020/9/3     17:13           6144 SQLitePCLRaw.batteries_v2.dll
-a----          2020/9/3     17:13          46592 SQLitePCLRaw.core.dll
-a----          2020/9/3     17:13           5632 SQLitePCLRaw.nativelibrary.dll
-a----          2020/9/3     17:13          57344 SQLitePCLRaw.provider.dynamic_cdecl.dll
-a----        2019/11/15      8:37         375912 System.Configuration.ConfigurationManager.dll
-a----         2018/5/15     13:29          46224 System.Diagnostics.PerformanceCounter.dll
-a----         2020/6/30      1:03          83304 System.IdentityModel.Tokens.Jwt.dll
-a----        2019/11/15      8:37         118344 System.IO.Packaging.dll
-a----        2019/11/15      8:37          83528 System.Runtime.Caching.dll
-a----        2019/11/15      8:37          17784 System.Security.Cryptography.ProtectedData.dll
-a----         2016/11/5      4:57         118680 System.Xml.XPath.XmlDocument.dll
-a----         2021/2/26     17:50         355328 ZKEACMS.dll
-a----         2021/2/26     17:50         170196 ZKEACMS.pdb
-a----         2021/2/26     17:50         234521 ZKEACMS.WebHost.deps.json
-a----         2021/2/26     17:50          20480 ZKEACMS.WebHost.dll
-a----         2021/2/26     17:50         142848 ZKEACMS.WebHost.exe
-a----         2021/2/26     17:50          23396 ZKEACMS.WebHost.pdb
-a----         2021/2/26     17:50            174 ZKEACMS.WebHost.runtimeconfig.dev.json
-a----         2021/2/26     17:50            354 ZKEACMS.WebHost.runtimeconfig.json
-a----         2021/2/26     17:50         730624 ZKEACMS.WebHost.Views.dll
-a----         2021/2/26     17:50         120640 ZKEACMS.WebHost.Views.pdb
```

SDK版本：
> .NET SDK (反映任何 global.json):
 Version:   5.0.102
 Commit:    71365b4d42
运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

ZKEACMS Git版本：
> commit 70d5408251e70ca96d2a119e319f67396837a84c (HEAD -> master, tag: v3.3.7, origin/master, origin/HEAD)
Author: wayne <seriawei@outlook.com>
Date:   Fri Jan 22 20:24:29 2021 +0800
        Display all columns if entity has no metadata

**Comment by SeriaWei** [comment]
使用5000端口访问，默认是5000端口。

如果要使用dotnet命令，需要在 `./src/ZKEACMS.WebHost` 目录下运行:
```
set ASPNETCORE_ENVIRONMENT=Development
dotnet bin/Debug/net5.0/ZKEACMS.WebHost.dll
```
参考[Run.cmd](https://github.com/SeriaWei/ZKEACMS/blob/master/src/ZKEACMS.WebHost/Run.cmd)

**Comment by brack7n** [comment]
:(
浏览器访问链接为`http://localhost:5000`,返回状态码`302`自动跳转至`https://localhost:5001/`然后出现错误。
对比publish的版本
publish的版本会从`http://localhost:5000`跳转至`https://localhost:5001/`再跳转至`https://localhost:5001/index`正常访问首页。

VS2019调试启动问题依旧。

命令行运行提示以下错误：
```
PS G:\> cd .\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost\
PS G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost> set ASPNETCORE_ENVIRONMENT=Development
PS G:\Source\Repos\ZKEACMS\src\ZKEACMS.WebHost> dotnet bin/Debug/net5.0/ZKEACMS.WebHost.dll
All plugins are loaded. Elapsed: 2ms
Welcome to use ZKEACMS
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: Fail to create ZKEACMS,ZKEACMS.Common.Service.CarouselWidgetService instance. May be the plugin is not exists or not regist.
         at ZKEACMS.Widget.DefaultWidgetActivator.Create(WidgetBase widget) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\DefaultWidgetActivator.cs:line 46
         at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>b__3(WidgetBase widget) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 59
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>g__getPageWidgets|0(PageEntity p) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 59
         at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>b__1(String key, String region) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 63
         at CacheManager.Core.BaseCacheManager`1.<>c__DisplayClass84_0.<GetOrAdd>b__0(String k, String r)
         at CacheManager.Core.BaseCacheManager`1.GetOrAddInternal(String key, String region, Func`3 valueFactory)
         at CacheManager.Core.BaseCacheManager`1.GetOrAdd(String key, String region, Func`3 valueFactory)
         at Easy.Cache.DefaultCacheManager`1.GetOrAdd(String key, String region, Func`3 valueFactory) in G:\Source\Repos\ZKEACMS\src\EasyFrameWork\Cache\DefaultCacheManager.cs:line 48
         at ZKEACMS.Widget.WidgetBasePartService.GetAllByPage(PageEntity page) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 63
         at ZKEACMS.Filter.WidgetAttribute.OnActionExecuted(ActionExecutedContext filterContext) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Filter\WidgetAttribute.cs:line 103
         at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
`Logs`文件夹下日志：
```
----------------------------------------------------------------
Event Time: 2021/2/26 20:40:52
Error Message:
System.Exception: Fail to create ZKEACMS,ZKEACMS.Common.Service.CarouselWidgetService instance. May be the plugin is not exists or not regist.
   at ZKEACMS.Widget.DefaultWidgetActivator.Create(WidgetBase widget) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\DefaultWidgetActivator.cs:line 46
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>b__3(WidgetBase widget) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 59
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>g__getPageWidgets|0(PageEntity p) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 59
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass13_0.<GetAllByPage>b__1(String key, String region) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 63
   at CacheManager.Core.BaseCacheManager`1.<>c__DisplayClass84_0.<GetOrAdd>b__0(String k, String r)
   at CacheManager.Core.BaseCacheManager`1.GetOrAddInternal(String key, String region, Func`3 valueFactory)
   at CacheManager.Core.BaseCacheManager`1.GetOrAdd(String key, String region, Func`3 valueFactory)
   at Easy.Cache.DefaultCacheManager`1.GetOrAdd(String key, String region, Func`3 valueFactory) in G:\Source\Repos\ZKEACMS\src\EasyFrameWork\Cache\DefaultCacheManager.cs:line 48
   at ZKEACMS.Widget.WidgetBasePartService.GetAllByPage(PageEntity page) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 63
   at ZKEACMS.Filter.WidgetAttribute.OnActionExecuted(ActionExecutedContext filterContext) in G:\Source\Repos\ZKEACMS\src\ZKEACMS\Filter\WidgetAttribute.cs:line 103
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Method:GET
Headers:
:authority:localhost:5001
:method:GET
:path:/
:scheme:https
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.9
Cookie:UM_distinctid=177d2d94a6cabb-0da754a4408c4b-73e356b-384000-177d2d94a6dd14,CNZZDATA1260354294=1655260546-1614149534-%7C1614149534,last-notice=87
Host:localhost:5001
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Upgrade-Insecure-Requests:1
sec-fetch-site:none
sec-fetch-mode:navigate
sec-fetch-user:?1
sec-fetch-dest:document
sec-ch-ua:"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
sec-ch-ua-mobile:?0
/
----------------------------------------------------------------
----------------------------------------------------------------
```

**Comment by SeriaWei** [comment]
```
Starting...
Loading: ZKEACMS.Article
Loading: ZKEACMS.FormGenerator
Loading: ZKEACMS.GlobalScripts
Loading: ZKEACMS.Message
Loading: ZKEACMS.Product
Loading: ZKEACMS.Redirection
Loading: ZKEACMS.SectionWidget
Loading: ZKEACMS.Shop
Loading: ZKEACMS.Sitemap
Loading: ZKEACMS.SiteSearch
Loading: ZKEACMS.StyleEditor
Loading: ZKEACMS.Swagger
Loading: ZKEACMS.TemplateImporter
Loading: ZKEACMS.Updater
All plugins are loaded. Elapsed: 167ms
Welcome to use ZKEACMS
```
表示程序已经正常启动了。
从 `http://localhost:5000` -> `https://localhost:5001` 是不是浏览器缓存跳的？
你可以试试打开开发人员工具，然后禁用浏览器缓存后访问 `http://localhost:5000` 

![image](https://user-images.githubusercontent.com/6006218/109308331-d59c4c00-787c-11eb-87df-6188820ebac8.png)

或者换个端口。

**Comment by brack7n** [comment]
:)
解决
