### ISSUE TITLE
企业版本用仓库中mysql的dump.sql出错

### ISSUE THREAD

**Issue by goodtogood** [SeriaWei/ZKEACMS#447]
不错的CMS，在官网下了企业版本是用的sqlite数据库，想用下mysql看看，
操作如下把 mysql/dump.sql导入到建立的数据库，然后修改连接字串，
当访问首页时空白，错误日志如下

```
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `c`.`ID`, `c`.`AssemblyName`, `c`.`CreateBy`, `c`.`CreateDate`, `c`.`CreatebyName`, `c`.`Description`, `c`.`ExtendData`, `c`.`FormView`, `c`.`InnerStyle`, `c`.`IsSystem`, `c`.`IsTemplate`, `c`.`LastUpdateBy`, `c`.`LastUpdateByName`, `c`.`LastUpdateDate`, `c`.`LayoutID`, `c`.`PageID`, `c`.`PartialView`, `c`.`Position`, `c`.`RuleID`, `c`.`ServiceTypeName`, `c`.`Status`, `c`.`StyleClass`, `c`.`Thumbnail`, `c`.`Title`, `c`.`ViewModelTypeName`, `c`.`WidgetName`, `c`.`ZoneID`
FROM `CMS_WidgetBase` AS `c`
WHERE EXISTS (
    SELECT 1
    FROM `ArticleDetailWidget` AS `a`
    WHERE `a`.`ID` = `c`.`ID`)
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/index
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
MySqlConnector.MySqlException (0x80004005): Unknown column 'c.InnerStyle' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 319
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/index
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
MySqlConnector.MySqlException (0x80004005): Unknown column 'c.InnerStyle' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 319
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Easy.RepositoryPattern.ServiceBase`2.Get(Expression`1 filter) in D:\Projects\ZKEACMS.Enterprise\src\EasyFrameWork\RepositoryPattern\ServiceBase.cs:line 201
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.<GetRelatedPageUrls>b__10_0(String fac) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 111
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.GetRelatedPageUrls() in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 109
   at ZKEACMS.Article.ArticleRouteDataProvider.ExtractVirtualPath(String path, RouteValueDictionary values) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\ArticleRouteDataProvider.cs:line 34
   at ZKEACMS.PageRouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Route\PageRouteConstraint.cs:line 29
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessConstraints(Endpoint endpoint, KeyValuePair`2[] constraints, HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at ZKEACMS.MultiLanguage.LocalizeRedirectMiddleware.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\MultiLanguage\LocalizeRedirectMiddleware.cs:line 82
   at ZKEACMS.Page.StaticPageMiddleWare.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Page\StaticPageMiddleWare.cs:line 86
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/index
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `c`.`ID`, `c`.`AssemblyName`, `c`.`CreateBy`, `c`.`CreateDate`, `c`.`CreatebyName`, `c`.`Description`, `c`.`ExtendData`, `c`.`FormView`, `c`.`InnerStyle`, `c`.`IsSystem`, `c`.`IsTemplate`, `c`.`LastUpdateBy`, `c`.`LastUpdateByName`, `c`.`LastUpdateDate`, `c`.`LayoutID`, `c`.`PageID`, `c`.`PartialView`, `c`.`Position`, `c`.`RuleID`, `c`.`ServiceTypeName`, `c`.`Status`, `c`.`StyleClass`, `c`.`Thumbnail`, `c`.`Title`, `c`.`ViewModelTypeName`, `c`.`WidgetName`, `c`.`ZoneID`
FROM `CMS_WidgetBase` AS `c`
WHERE EXISTS (
    SELECT 1
    FROM `ArticleDetailWidget` AS `a`
    WHERE `a`.`ID` = `c`.`ID`)
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/Error
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
MySqlConnector.MySqlException (0x80004005): Unknown column 'c.InnerStyle' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 319
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/Error
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
MySqlConnector.MySqlException (0x80004005): Unknown column 'c.InnerStyle' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 319
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Easy.RepositoryPattern.ServiceBase`2.Get(Expression`1 filter) in D:\Projects\ZKEACMS.Enterprise\src\EasyFrameWork\RepositoryPattern\ServiceBase.cs:line 201
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.<GetRelatedPageUrls>b__10_0(String fac) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 111
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.GetRelatedPageUrls() in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 109
   at ZKEACMS.Article.ArticleRouteDataProvider.ExtractVirtualPath(String path, RouteValueDictionary values) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\ArticleRouteDataProvider.cs:line 34
   at ZKEACMS.PageRouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Route\PageRouteConstraint.cs:line 29
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessConstraints(Endpoint endpoint, KeyValuePair`2[] constraints, HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at ZKEACMS.MultiLanguage.LocalizeRedirectMiddleware.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\MultiLanguage\LocalizeRedirectMiddleware.cs:line 82
   at ZKEACMS.Page.StaticPageMiddleWare.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Page\StaticPageMiddleWare.cs:line 86
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/Error
----------------------------------------------------------------
----------------------------------------------------------------
Event Time: 2021-12-04 22:59:46
Error Message:
MySqlConnector.MySqlException (0x80004005): Unknown column 'c.InnerStyle' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 319
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Easy.RepositoryPattern.ServiceBase`2.Get(Expression`1 filter) in D:\Projects\ZKEACMS.Enterprise\src\EasyFrameWork\RepositoryPattern\ServiceBase.cs:line 201
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.<GetRelatedPageUrls>b__10_0(String fac) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 111
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ZKEACMS.Article.Service.ArticleDetailWidgetService.GetRelatedPageUrls() in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\Service\ArticleDetailWidgetService.cs:line 109
   at ZKEACMS.Article.ArticleRouteDataProvider.ExtractVirtualPath(String path, RouteValueDictionary values) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS.Article\ArticleRouteDataProvider.cs:line 34
   at ZKEACMS.PageRouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Route\PageRouteConstraint.cs:line 29
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessConstraints(Endpoint endpoint, KeyValuePair`2[] constraints, HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at ZKEACMS.MultiLanguage.LocalizeRedirectMiddleware.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\MultiLanguage\LocalizeRedirectMiddleware.cs:line 82
   at ZKEACMS.Page.StaticPageMiddleWare.Invoke(HttpContext context) in D:\Projects\ZKEACMS.Enterprise\src\ZKEACMS\Page\StaticPageMiddleWare.cs:line 86
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Method:GET
Headers:
Cache-Control:max-age=0
Connection:keep-alive
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:.AspNetCore.Antiforgery.Ql8D23Fg084=CfDJ8MyYOxoFlZhAhutBAly2zknJKnO88gq37Utxvfv84jK264PovustC0fufRVFsPhpMYpbNJoq0ZWZO83HpWkGlkm3rQa6zO1Bz4r2L6-i5ds4wV91o4H8fcOoKGE5u5v73pmKyCa-Ggmb7q3ANhVT8nQ
Host:127.0.0.1:5000
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Upgrade-Insecure-Requests:1
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:none
Sec-Fetch-User:?1
/index
----------------------------------------------------------------
```

**Comment by goodtogood** [comment]
已经找！
